server {
	listen 8080;
	server_name localhost;

	error_page 404 /404.html;
	error_page 500 502 503 504 /50x.html;
	client_max_body_size 1000000;

	keepalive_timeout 65;

	location / {
		root ./www;
		index index.html;
		methods GET;
	}

	location /old {
		return 301 /new;
	}

	location /new {
		root ./www;
		index new.html;
		methods GET;
	}

	location /upload {
		root ./files;
		methods POST;
	}

	location /files {
		root ./files;
		autoindex on;
		methods GET;
	}

	location /cgi {
		root ./cgi-bin;
		cgi .py /usr/bin/python3;
	}
}


	# another virtual host using mix of IP-, name-, and port-based configuration
	#
	#server {
	#    listen       8000;
	#    listen       somename:8080;
	#    server_name  somename  alias  another.alias;

	#    location / {
	#        root   html;
	#        index  index.html index.htm;
	#    }
	#}

