server {
   listen       3131;
   server_name  localhost;

   location / {
       root   ./test;
       autoindex on;
   }
   location /mypy {
        root ./test/mypy;
        index index.py;
        cgi .py /usr/bin/python3;
   }
}