name: Make and Test

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    make-and-test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: update and install dependencies
          run: sudo apt-get update

        - name: Set up C++ environment
          run: sudo apt-get install build-essential

        - name: Build the project
          run: make

        - name: Run tests
          id: test_step
          shell: bash
          run: |
            chmod +x ./tester ./cgi_tester
            
            # Start webserv in background and redirect output to output.txt
            ./webserv test.conf > server_output.txt 2>&1 &
            SERVER_PID=$!
            
            # Wait for the server to start listening (up to 10 seconds)
            echo "Waiting for webserv to start..."
            for i in {1..10}; do
              if nc -z localhost 3131; then
                echo "webserv is up and listening on port 3131."
                break
              fi
              sleep 1
            done
            
            # Run the tester and log to console + tester_output.txt
            echo "Running tester..."
            ./tester http://localhost:3131 > tester_output.txt 2>&1
            TEST_EXIT_CODE=$?
            cat tester_output.txt
            
            # Terminate the server
            echo "Stopping webserv..."
            kill $SERVER_PID || true  
            
            # Export the test status
            echo "test_status=$TEST_EXIT_CODE" >> $GITHUB_ENV

        - name: Upload login debug artifacts
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: server_output.txt
            path: ./server_output.txt
            if-no-files-found: ignore
            retention-days: 1

        - name: Upload login debug artifacts
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: tester_output.txt
            path: ./tester_output.txt
            if-no-files-found: ignore
            retention-days: 1

        - name: Cancel workflow quietly if tests failed
          if: env.test_status != '0'
          uses: andymckay/cancel-action@0.5